Add recommendations
AGolykh/java-filmorate pull request #13
Opened 2023-04-13 19:39 UTC by AleksandrKis

Алгоритм работает и предсказывает !

2023-04-14 07:07 UTC, AGolykh requested changes

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public List<Film> getRecommendation(@PathVariable("id") Integer id) {
1) Предлагаю, как во всем проекте использовать Collection вместо List

2) если переменна пути в @GetMapping("/{id}/recommendations") называется так же как параметр метода (@PathVariable("id") Integer id), то такая запись излишняя, достаточно (@PathVariable Integer id)

3) у нас идентификаторs имеют тип Long, и переменную лучше не обезличивать, пускай будет userId

4) ну и сам эндпоинт лучше изменить по образу остальных     @GetMapping("/{userId}/recommendations")

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    public Map<Integer, Integer> getFilmsScore(Integer id) {
Нам нужна мапа идов фильмов, которые Long, и количество очков Integer, 
Потому сигнатура должна быть Map<Long, Integer>, и опять таки тип входных данных и имя переменной

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
Лишняя строка

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Film> filmsByIds(List<Integer> idFilmRecommended);
Сигнатуру нужно сделать, как во всем проекте

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +
Сигнатуры нужно изменить

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +
Если мы возвращаем массив данных, то должна быть Collection, если переменная - это идентификатор, то Long

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    public List<Film> filmsByIds(List<Integer> idFilmRecommended) {
Сигнатура метода

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    public List<Film> filmsByIds(List<Integer> idFilmRecommended) {
И это ведь метод не только по поиску рекомендованных фильмов, а просто поиск всех фильмов по переданной коллекции идентификаторов, потому переменную лучше назвать просто filmIds

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> convertIdsToFilms(List<Integer> idFilmRecommended) {
Сигнатура метода

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    public Map<Integer, List<Integer>> getDiffFilms(Integer id) {
Снова сигнатуры и типы переменных

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                    filmsScore.put(filmId, score);
Здесь не обязательно создавать переменные, лучше сразу передавать в метод 

filmsScore.put(rs.getLong("FILM_ID"), rs.getInt("SCORE"));

Все иды должны быть лонг

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                new MapSqlParameterSource("ID", id),
Не стоит обезличивать переменные, должно быть USER_ID, и в запросе соответственно :USER_ID

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                    filmLikeByUserId.computeIfAbsent(userId, l -> new ArrayList<>()).add(filmId);
Иды все лонговые

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                new MapSqlParameterSource().addValue("ID", id),
Снова обезличил id

2023-04-14 07:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        final List<Integer> maxCommonUsersId = userStorage.convertMaxCommonLikes(id);
Сигнатура метода и типы переменных

2023-04-14 11:12 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public List<Film> getRecommendation(@PathVariable("id") Integer id) {
Done !

2023-04-14 12:40 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    public Map<Integer, Integer> getFilmsScore(Integer id) {
Done !

2023-04-14 12:40 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +
Done !

2023-04-14 12:41 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Film> filmsByIds(List<Integer> idFilmRecommended);
Done !

2023-04-14 12:41 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +
Done !

2023-04-14 12:47 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    public List<Film> filmsByIds(List<Integer> idFilmRecommended) {
Done !

2023-04-14 12:47 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> convertIdsToFilms(List<Integer> idFilmRecommended) {
Done !

2023-04-14 12:47 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    public Map<Integer, List<Integer>> getDiffFilms(Integer id) {
Done !

2023-04-14 13:22 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                    filmsScore.put(filmId, score);
Done !

2023-04-14 13:23 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                new MapSqlParameterSource("ID", id),
Done !

2023-04-14 13:24 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                    filmLikeByUserId.computeIfAbsent(userId, l -> new ArrayList<>()).add(filmId);
Done !

2023-04-14 13:26 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                new MapSqlParameterSource().addValue("ID", id),
Done !

2023-04-14 13:28 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        final List<Integer> maxCommonUsersId = userStorage.convertMaxCommonLikes(id);
Done !

2023-04-15 05:12 UTC, AGolykh approved these changes

2023-04-15 05:12 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Collection<Film> filmsByIds(Collection<Long> idFilmRecommended);
В классе поменял имя переменной, а в интерфейсе забыл

2023-04-15 07:05 UTC, merged