Add feed
AGolykh/java-filmorate pull request #15
Opened 2023-04-15 13:04 UTC by nikita-garkusha

Без отслеживания отзывов

2023-04-15 19:18 UTC, AGolykh requested changes

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +    @GetMapping("/{id}/feed")
Не стоит обезличивать переменные, даже если это переменная - единственная в классе, пусть будет eventId

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +
Лишняя строка

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +@Data
В аннотацию Data уже входят геттеры и сеттеры, так что ниже аннотации излишни

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    Integer eventId;
Идентификаторы все лонговые должны быть

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/model/enums/EventType.java
> +public enum EventType {
Так как enum используется только в классе  event, то стоит его сделать внутренним

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/model/enums/Operation.java
> +public enum Operation {
То же что и выше

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/EventService.java
> +    public Collection<Event> getFeed(long userId) {
лучше не использовать приметив для идентификаторов

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
Лишняя строка

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .eventId(null)
Зачем сеттить через билдер нуллевое значение в идентификатор, билдер позволяет заполнять не все поля, значение этого поле создастся в базе

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .eventType(EventType.LIKE)
в случае перемещения enum в класс эвента придется переписать обращение к enum

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .eventId(null)
лишнее

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                    .eventId(null)
Лишнее

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                    //.userId(review.getUserId())
лучше убрать закомментированный квест

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                    .eventId(null)
Лишнее

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .eventId(null)
Пропало логгирование
нулл лишний

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .eventId(null)
лишнее

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/EventStorage.java
> +    Collection<Event> getFeed(Long id);
Обезличена переменная

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/EventDBStorage.java
> +    private final JdbcTemplate jdbcTemplate;
Попробуй использовать NamedJdbcTemplate, как во всем проекте, это удобнее

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/EventDBStorage.java
> +    public EventDBStorage(DataSource dataSource) {
При использовании аннотации @RequiredArgsConstructor такой конструктор будет лишним

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    Long timestamp;
Почему не Timestamp?

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/EventDBStorage.java
> +            .timestamp(rs.getLong("TIMESTAMP"))
Тут можно будет тогда rs.getTimestamp юзать

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/EventDBStorage.java
> +        return jdbcTemplate.query(query, new Object[]{id}, eventMapper);
Тут при именованном jdbcTemplate придется переделать, 
в подобном запросе можно и обычным темплейтом отделаться, но если будет много переменных в запросе, то куча ???? в запросе могут стать проблемой для восприятия

2023-04-15 19:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FriendDbStorage.java
> +
Лишняя строка

2023-04-15 19:18 UTC, AGolykh commented on src/main/resources/schema.sql
> +    ENTITY_ID  INT NOT NULL
это идентификатор, так что лучше bigint

2023-04-15 20:54 UTC, nikita-garkusha commented on src/main/java/ru/yandex/practicum/filmorate/model/Event.java
> +    Long timestamp;
Тесты постмана всё равно считывают число, а не дату. Поэтому думаю проще сразу в бд кидать Long напрямую и не преобразовывать его из Timestamp и обратно

2023-04-16 05:25 UTC, AGolykh approved these changes

2023-04-16 05:39 UTC, merged