Develop
AGolykh/java-filmorate pull request #16
Opened 2023-04-16 05:47 UTC by AGolykh

Выполнены все обязательные задачи

2023-04-17 10:31 UTC, TomattmanYandex requested changes
большая задача, сложная, но сделано хорошо,
комментарии в пулл реквесте
а теперь есть один комментарий, который заставит вас страдать потому что у вас это много где используется
"не допускаются запросы с двумя вложенными подзапросами. Их надо переписать с использованием join. "

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
эта аннотация помечена как экспериментальная фича, а экспериментальные фичи иногда использовать не стоит
но тут сойдет

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (rev.getUserId() != null && rev.getReviewId() != null) {
что за eventService, как минимум по требованиям такого не нахожу

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (review.getUserId() != null && review.getReviewId() != null) {
не совсем логично что в начале проверяется существует ли запись в базе, и только после этого проверяем null поля или нет
Лучше сначала проверить на null если null то прокинуть ошибку, потом проверить на существование в базе, а уже потом делать все проверки

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (result.isPresent()) {
проверьте случай попытки удаления ревью, если у него есть лайки и дизлайки, не повалится ли тогда запрос из-за наличия связей?

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        assertReviewMarkNotExists(reviewId, userId, true);
кажется с текущей проверкой один пользователь может оставить сразу лайк и дизлайк к одному ревью

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void addLikeToReview(Long reviewId, Long userId) {
так как лайк и дизлайк отличаются по boolean 
почему бы не сделать отдельный приватный метод, который будет принимать текущие два параметра и третий boolean  который будет иметь то же тело как эти два метода (надо их немного порефакторить)
а этот и следующий метод будут иметь по одной строчке, вызов нового метода с парfметром true или false

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void deleteReviewLike(Long reviewId, Long userId) {
и снова, может быть ситуация когда от одного пользователя одному ревью стоит сразу лайк и дизлайк, и когда она исправится, то этот и следующий метод можно будет объединить в один, ну или сделать как рекомендовал выше, (сделать новый метод с третьим параметром, а в этих методах вызывать его с разными параметрами)

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +    public Optional<ReviewMark> addLikeToReview(Long reviewId, Long userId) {
этот и следующий метод отличаются одним параметром, зачем иметь два метода под одно и то же, если можно просто добавить этот параметр

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +    public Optional<ReviewMark> deleteReviewLike(Long reviewId, Long userId) {
аналогично

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +    public Optional<ReviewMark> findReviewMark(Long reviewId, Long userId, boolean isLike) {
а вот тут все ок

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +    CONSTRAINT FK_REVIEWS_USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID) ON DELETE CASCADE,
тут тоже можно было бы добавить уникальность по комбинации фильма и пользователя, чтобы не было возможности наклепать кучу ревью на один фильм одним пользователем

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/search")
запрос должен быть просто /search а не /films/search

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Collection<Film> result = null;
Почему бы не сделать Set для уникальности
если в параметрах есть директор, то добавляем результат поиска по директору, если в параметре есть тайтл то в результат добавляем поиск по тайтлу, если в параметре оба значения, то уже все обработано
а то что добавлено в SET - значит что не будет повторений
Это будет гораздо лучше, потому что если мы добавим возможность поиска еще по какому то параметру, то сейчас придётся добавить несколько блоков if else, а с предложенным мной решением - только один

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return filmService.convertIdsToFilms(userService.findAdviseFilmsIds(userId));
лучше сделать чтобы один сервис ссылался на другой, 
т.е. вызываем метод в фильм сервисе с параметром userId
фильм сервис вызывает у юзер сервиса метод userService.findAdviseFilmsIds(userId)
и дальше работает с результатом который вернулся

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> convertIdsToFilms(Collection<Long> filmsIds) {
с текущей реализацией я бы назвал этот метод findFilmByIds
а вообще можно перегрузить метод find
с параметром long - поиск по id
с параметром List<Long> поиск по нескольким id
с параметрами String subString, List<String> by - поиск по этим данным
без параметров - поиск всех

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Map<Long, Film> filmMap = resultAdvise.stream().collect(Collectors.toMap(Film::getId, Function.identity()));
1- зачем работать с collection если можно возвращать либо лист либо сет либо конкретную реализацию (но луче либо лист либо сет)
2 - зачем эти дополнительный танцы  с бубном по переводу в мапу а из нее переводу в коллекцию?

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                "SELECT USER_ID, COUNT(FILM_ID) SCORE " +
в запросе можно сразу задать сортировку и лимит возвращенных записей

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    public Map<Long, List<Long>> getDiffFilms(Long userId) {
не понятно назначение этого метода

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        final Map<Long, List<Long>> filmDiffByUser = userStorage.getDiffFilms(userId);
у нас есть id пользователя и id всех пользователей с которыми максимальное количество совпадений, почему мы делаем запрос только по одному id ?

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        final Map<Long, List<Long>> filmDiffByUser = userStorage.getDiffFilms(userId);
в этом методе по сути должно быть два основных момента
получили пользователей с наибольшим количеством совпадений, одним запросом, вторым запросом получили id фильмов для рекомендаций

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +    public Collection<Event> getFeed(@PathVariable Long eventId) {
это event id или user id тут именуется как event в сервисе принимается user

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        eventService.addEvent(Event.builder()
1) зачем добавлять в билдер строчку .eventId(null) без нее и  так должно быть null
2) почему бы не вынести это действо в отдельный приватный метод c кучкой параметров

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            eventService.addEvent(Event.builder()
комент тот же что и в другом классе, почему бы это не вынести в отдельный метод,  и не перегружать текущий метод дополнительным функционалом

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                    .userId(1L) //ВНИМАНИЕ! КОСТЫЛЬ! ОШИБКА В ТЕСТАХ ПОСТМАНА!
что за ошибка? напишите наставнику о ней, ну или скажите что за ошибка, я сам напишу

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        eventService.addEvent(Event.builder()
и снова, вынести бы это в отдельный метод

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Optional<User> result = userStorage.findById(userId);
а работает ли, есть у пользователя есть друзья и лайки, не падает ли с ошибкой попытки удаления связанных данных

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        jdbcTemplate.update(
а работает ли, если у фильма есть лайки, жанры, и другие связанные данные?

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    public Collection<Film> findFilmsDirectorByYear(Long directorId) {
вроде как этот и следующий метод должны отличаться только сортировкой но почему то очень большая разница в них

2023-04-17 10:31 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (rev.getUserId() != null && rev.getReviewId() != null) {
ах я позже выяснил что за он, не обращайте внимания

2023-04-17 10:52 UTC, AGolykh commented on src/main/resources/schema.sql
> +    CONSTRAINT FK_REVIEWS_USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS (USER_ID) ON DELETE CASCADE,
Исправлено

2023-04-17 11:55 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Optional<User> result = userStorage.findById(userId);
Функционал покрыт тестами, юзеры с лайками и друзьями нормально удаляются, потому как в constrain прописано on delete cascade;

2023-04-17 12:08 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        jdbcTemplate.update(
Функционал покрыт тестами, фильмы с лайками и режиссерами нормально удаляются, потому как в constrain прописано on delete cascade;

2023-04-17 19:40 UTC, exipse commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/search")
По ТЗ URL должен быть: GET /films/search

2023-04-18 05:17 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (review.getUserId() != null && review.getReviewId() != null) {
Исправлено

2023-04-18 05:17 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (result.isPresent()) {
Добавлен тест, проходит нормально

2023-04-18 06:39 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        assertReviewMarkNotExists(reviewId, userId, true);
Исправлено

2023-04-18 06:40 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void addLikeToReview(Long reviewId, Long userId) {
Исправлено

2023-04-18 06:40 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void deleteReviewLike(Long reviewId, Long userId) {
Исправлено

2023-04-18 06:40 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +    public Optional<ReviewMark> addLikeToReview(Long reviewId, Long userId) {
Исправлено

2023-04-18 06:40 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDbStorage.java
> +    public Optional<ReviewMark> deleteReviewLike(Long reviewId, Long userId) {
Исправлено

2023-04-18 06:42 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +                    .userId(1L) //ВНИМАНИЕ! КОСТЫЛЬ! ОШИБКА В ТЕСТАХ ПОСТМАНА!
РАзобрались, проблема была в том, что в json отправлялись измененные юзер ид и фильм ид, а они апдейтиться не должны

2023-04-18 06:42 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    public Collection<Film> findFilmsDirectorByYear(Long directorId) {
Исправлено

2023-04-18 07:11 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Collection<Film> result = null;
Cделано

2023-04-18 11:40 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FeedController.java
> +    public Collection<Event> getFeed(@PathVariable Long eventId) {
Исправлено

2023-04-18 12:27 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        eventService.addEvent(Event.builder()
Исправлено

2023-04-18 12:27 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            eventService.addEvent(Event.builder()
Исправлено

2023-04-18 12:29 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        eventService.addEvent(Event.builder()
Исправлено

2023-04-18 15:54 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return filmService.convertIdsToFilms(userService.findAdviseFilmsIds(userId));
Done!

2023-04-18 15:55 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Collection<Film> convertIdsToFilms(Collection<Long> filmsIds) {
- назвал этот метод findFilmByIds !

2023-04-18 17:10 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Map<Long, Film> filmMap = resultAdvise.stream().collect(Collectors.toMap(Film::getId, Function.identity()));
1.collection - возвращается для соблюдения однородности проекта.
2...этот танец на стёклах соблюдения порядка сортировки ради ибо приходит результат с важной сортировкой по наибольшей вероятности понравится к наименьшей и после актуализации из чисел в фильмы этот порядок утрачивается .

2023-04-18 17:53 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +                "SELECT USER_ID, COUNT(FILM_ID) SCORE " +
Для создания листа пользователей с максимальной идентичностью по вкусам, с заданным пользователем, но без учёта самого пользователя. Поддержкой возможности выборки из неопределённого количества возможных претендентов и попыткой предусмотреть ситуации с отсутствием таковых...
Мне вдохновленному [статьёй ](https://www.baeldung.com/java-collaborative-filtering-recommendations) о матрице предсказания , показался этот способ наиболее уместным, в сложившейся ситуации , однако я не тешу себя мыслью о единственно верном решении и даже более того уверен что это не так, но увы , лишь сей уровень ваш покорный слуга достиг и Вам благодаря его повышаю.
 А посему смиренно приму наставления и сделаю так как Вам покажется верным.

2023-04-18 18:07 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    public Map<Long, List<Long>> getDiffFilms(Long userId) {
Этот метод есть основа предсказания, если позволите так называть результат работы алгоритма . Метод с помощью запроса к Базе  формирует Мапу - filmLikeByUserId, ключом которой есть идентификатор пользователя который схож с заданным пользователем по вкусам , а значением этой мапы Лист фильмов которые этот пользователь отметил Лайком (без учёта фильмов отмеченных заданным пользователем) как только Мапа сформирована она уходит в UserService где и становится основой предсказания.

2023-04-18 18:53 UTC, AleksandrKis commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        final Map<Long, List<Long>> filmDiffByUser = userStorage.getDiffFilms(userId);
Метод **_findAdviseFilmsIds_** по сути есть квинтэссенция алгоритма.
  Он преобразует Мапу с "_похожими_"пользователями и листами "их" фильмов, преобразует путём фильтрации с помощью листа максимально "_похожих_" на заданного пользователя(**_maxCommonUsersId_**) и сортирует результат используя Мапу с рейтингом "_залайконости_" фильмов (без учёта заданного пользователя) **_scoreByFilms_**.
На выходе получается отсортированный лист идентификаторов, от самого вероятно интересного (для заданного пользователя) до вероятно менее интересного но всё же предсказано интересного, фильмов .
Который в свою очередь отправляется в **_FilmService_** где и будет актуализирован из листа чисел в лист фильмов.
   По факту, действительно алгоритм можно сократить до получения листа "_похожих_" и вывода отмеченных ими фильмов, благо ТЗ не регламентирует подобные изыски.
 Но всё же если можно отсортировать полученный список в порядке предсказанной интересности мне показалось это в полне в духе [статьи ](https://www.baeldung.com/java-collaborative-filtering-recommendations)которую нам рекомендовали в ТЗ?
Однако я сделаю как Вы считаете верным.

2023-04-19 10:08 UTC, TomattmanYandex requested changes
еще чуть чуть подправить

2023-04-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        eventService.addEvent(rev.getUserId(), rev.getReviewId(), EventType.REVIEW, Operation.ADD);
отлично, вариант как можно еще немного изменить, сделать в этом классе метод который будет вызывать метод из класса eventService но у метода в текущем классе будет на один параметр меньше, так как тип всегда будет REVIEW

2023-04-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        assertReviewMarkNotExists(reviewId, userId, isLike);
Кажется еще не исправлена проблема с тем, что один пользователь может ставить сразу лайк и дизлайк одному и тому же ревью

2023-04-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Optional<Review> result = reviewStorage.createReview(review);
я бы тут добавил проверку что ревью на этот фильм от этого пользователя не существует, ибо упадет с ошибкой из-за нового ограничения уникальности

2023-04-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.findAdviseFilms(userId);
лучше все же наоборот, так как мы ищем фильмы, чтобы основной метод был в фильм сервисе, а использовал он мет од из юзер сервиса

2023-04-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Map<Long, Film> filmMap = resultAdvise.stream().collect(Collectors.toMap(Film::getId, Function.identity()));
1) обычно везде используется все же конкретная коллекция например LIst, и так обычно используется то что лучше всего подходит? использование Collection вместо того же LIst обычно избыточно, так как при использовании придётся приводить к какому то типу
2) понял, зачем, но разве в методе addDataFilms теряется порядок, там же мы никак не перелопачиваем список фильмов, возможно если бы метод принимал не Collection а LIst то порядок бы сохранялся

2023-04-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +    public Map<Long, List<Long>> getDiffFilms(Long userId) {
звучит сложно 
если будет тест на логику предсказаний то почему бы не принято, но обычно решения попроще гораздо лучше, за счет того, что хорошо понимаешь текущую задачу скорее всего только ты, и если кому то еще надо будет что то с ней сделать, то ему придется поднапрячься чтобы ее понять

2023-04-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Optional<User> result = userStorage.findById(userId);
окок, отлично

2023-04-19 10:08 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        final Map<Long, List<Long>> filmDiffByUser = userStorage.getDiffFilms(userId);
я уже писал на этот счет, если есть тест который это покрывает, то будет принято, но полегче решения обычно лучше

2023-04-19 10:08 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/service/GetPopularFilmTest.java
> +    void getPopularFilmsWith2Count_return2Films_added5FilmsWithLikes() {
именуем методы немного не так
имя тестируемого метода_что должно быть_условия
тут With2Count это больше походе на условие

2023-04-19 10:41 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        eventService.addEvent(rev.getUserId(), rev.getReviewId(), EventType.REVIEW, Operation.ADD);
добавлены методы в ревью, фильмы и юзеры

2023-04-19 10:45 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.findAdviseFilms(userId);
Реализация метода изменена

2023-04-19 10:58 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Optional<Review> result = reviewStorage.createReview(review);
Добавлена проверка на отсутствие ревью

2023-04-19 11:12 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        assertReviewMarkNotExists(reviewId, userId, isLike);
Добавлена проверка, если отметка к ревью с указанным пользователем и противоположной отметкой имеется, то апдейт отметки

2023-04-19 11:54 UTC, AGolykh commented on src/test/java/ru/yandex/practicum/filmorate/service/GetPopularFilmTest.java
> +    void getPopularFilmsWith2Count_return2Films_added5FilmsWithLikes() {
Исправлены все названия тестов

2023-04-19 15:22 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userService.findAdviseFilms(userId);
Трассировка данных: FilmDBStorage -> FilmService -> UserService -> UserController

2023-04-20 11:58 UTC, TomattmanYandex approved these changes
Принято

2023-04-20 12:28 UTC, merged