Controllers films users
AGolykh/java-filmorate pull request #2
Opened 2023-02-06 18:46 UTC by AGolykh

2023-02-06 21:13 UTC, TomattmanYandex requested changes

2023-02-06 21:13 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
Давай исправим с примитива на класс обертку
Я думаю в предыдущих работах писал почему это лучше, но повторюсь, 
обертка хранит дополнительное значение null которое может означать что его не проставили

2023-02-06 21:13 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @EqualsAndHashCode.Exclude
зачем исключать неоторые поля?

2023-02-06 21:13 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(String name, String description, String releaseDate, int duration) {
Хватило бы сгенерированного @AllArgsConstructor но можно и так

2023-02-06 21:13 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @EqualsAndHashCode.Exclude
А, все понял, но такое используется не очень часто, обычно все же equals и hashCode считаются по всем полям, а такие проверки делаются либо в валидации либо руками на уровне сервиса

2023-02-06 21:13 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +    public static boolean validate(Film film) {
тут все хорошо, но в качестве дополнения можно было бы в ошибке  указать сразу все проблемы валидации, гораздо удобнее, чем когда ты получаешь исправляешь что то, а потом снова ошибка но уже новая

2023-02-06 21:13 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if(!FilmValidator.validate(film)) {
это конструкция слегка бессмысленна, так как метод validate в случае не валидного значение кидает ошибку, следовательно все что будет дальше будет проигнорировано
Плюс по условию должны быть логи, следует отловить ошибку и вывести логи

2023-02-06 21:13 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if(films.containsValue(film)) {
вот это, и такой же момент в других методах, и в другом контроллере, это усложнение, которое не факт что надо, может в дальнейшем привести к сложностям. Тем более скорее всего дальше надо будет подвигать это на другой уровень.
Можно не изменять, это просто наблюдение)))

2023-02-06 21:13 UTC, TomattmanYandex commented on src/main/resources/application.properties
> +logging.level.org.zalando.logbook.Logbook=DEBUG
а вот я люблю yaml формат конфигов)))

2023-02-07 04:35 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
Исправлено, в Film делал обертку, тут почему-то забыл

2023-02-07 06:02 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(String name, String description, String releaseDate, int duration) {
Мне этот конструктор нужен, так как по умолчанию Duration считает секунды, а мне нужно, что бы из json он парсил минуты

2023-02-07 09:04 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +    public static boolean validate(Film film) {
Готово, сделал с помощью StringBuilder

2023-02-07 11:24 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if(films.containsValue(film)) {
Исправлено

2023-02-07 11:25 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @EqualsAndHashCode.Exclude
Изменил реализацию

2023-02-07 11:25 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if(!FilmValidator.validate(film)) {
Исправлено

2023-02-07 17:25 UTC, TomattmanYandex requested changes
с валидацией прям перемудрил

2023-02-07 17:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) {
эхх, коментарии старые не остались после изменения

2023-02-07 17:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if(FilmValidator.validate(film, films)) {
в предыдущей версии было хорошая реализация
если валидация провалилась то возвращаем null 
если что то еще неправильно то возвращаем null
если все норм то обрабатываем как надо
так вложенность кода меньше и выглядит красивее и понятнее

2023-02-07 17:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private String ending() {
украшательства, они конечно делают логи красивыми, но во первых логи чаще всего пишут все же на английском, во вторых, это обычно техническая информация которая не должна быть прям красивой

2023-02-07 17:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film(String name, String description, String releaseDate, int duration) {
аа, отлично, принято

2023-02-07 17:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +        Integer hashOfFilm = film.getName().hashCode() + film.getReleaseDate().hashCode();
первую часть я понял, а вот то что начинается здесь, вообще не понял зачем
проверка с тем, есть ли такое значение в хранилище это не часть валидации, валидация, это проверка что поля соответствуют ограничениям

Вот эту часть и дальше можно удалить

2023-02-07 17:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/validator/UserValidator.java
> +        StringBuilder exceptionMessage = new StringBuilder();
тут то же самое, убрать эти мапы, они не нужны, тем более в валидаторе
Если хочется сделать сейчас проверку на то, что в хранилище уже есть такое значние или нет, то лучше сделать так же как и было, на уровне контроллера проверить
Просто в дальнейшем появится сервисный слой, который будет как прослойка между базой данных и уровнем контроллера, и вот эта вся логика уже будет там, а пока так как таких условий не было, лучше было просто не делать эту проверку

2023-02-07 17:25 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            film.setId(filmId++);
и снова коментарий по поводу валидации
сейчас у тебя валидатор ли кидает ошибку или возвращает true
логика будет какая

обьект валиден, тогда вернулось true обрабатываем,
обьект не валиден, приилетела ошибка и все что будет дальше все равно пропустится, и псоледняя строчка с return null тоже не выполнится
как можно сделать
просто вызвать метод validate и тогда если будет ошибка то дальше ничего не выполнится, если не будет, то выполнение продолжится

сейчас этот if не несет вообще никакой смысловой нагрузки

2023-02-07 17:25 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/validator/UserValidatorTest.java
> +    void validateUser_returnException_emailWithoutAt() {
эксепшены не возвращаются а прокидываются или генерируются
validateUser_throwException_emailWithoutAt
иногда лучше указывать даже какая ошибка, ибо может быть несоклько ошибок а в тесте проверяем на конкретную

2023-02-07 17:46 UTC, AGolykh commented on src/test/java/ru/yandex/practicum/filmorate/validator/UserValidatorTest.java
> +    void validateUser_returnException_emailWithoutAt() {
Исправил

2023-02-07 18:16 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private String ending() {
Поправил

2023-02-07 18:16 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
> +        Integer hashOfFilm = film.getName().hashCode() + film.getReleaseDate().hashCode();
Поправил

2023-02-07 18:50 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/validator/UserValidator.java
> +        StringBuilder exceptionMessage = new StringBuilder();
Исправил

2023-02-07 19:23 UTC, TomattmanYandex approved these changes
Отлично, принято

2023-02-07 20:21 UTC, merged