feat: Project 10 completed
AGolykh/java-filmorate pull request #3
Opened 2023-02-21 12:23 UTC by AGolykh

First iteration of project 10

2023-02-21 20:18 UTC, TomattmanYandex requested changes
Привет, все хорошо, из дополнительных моментов которые надо поправить - проблема с nullPointer - это частая ошибка и порой если она возникнет, будет не валидно показывать сообщение что не найдено, лучше, создать свое исключение и пробрасывать его

2023-02-21 20:18 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NullPointerException(String.format("Film %d is not found.", filmId));
лучше тут вернуть null, не стоит прокидывать лишний раз ошибки, все таки это исключительные ситуации

2023-02-21 20:18 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new NullPointerException(String.format("User %d is not found.", userId));
то же что и выше

2023-02-21 20:18 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(UserStorage userStorage, FilmStorage filmStorage) {
можно повесить на класс аннотацию @RequiredArgsConstructor и не создавать конструктор руками

2023-02-21 20:18 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> filterFilms(
согласно rest это должен быть путь тот же самый что и  получение всех, но с параметрами

2023-02-21 20:18 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        this.userStorage = userStorage;
обычно когда говорят про трехслойную архитектуру считается что слой контроллеров, лучше всего стобы знал о слое сервисов, а тот в свою очередь о слое хранилища, и желательно чтобы слои не пропусклись, т.е. лучше создать в сервисе метод findAll который будет просто вызывать метод findAll у хранилища, но при этом контроллер не будет знать о слое хранилища

2023-02-22 05:09 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NullPointerException(String.format("Film %d is not found.", filmId));
Исправлено

2023-02-22 05:09 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            throw new NullPointerException(String.format("User %d is not found.", userId));
Исправлено

2023-02-22 05:12 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NullPointerException(String.format("Film %d is not found.", filmId));
Но в таком случае тесты постмана не проходят, так как он ожидает 404 
![image](https://user-images.githubusercontent.com/114491672/220528358-e900d8dc-f60b-4545-9a68-68fcde2ccfb6.png)

2023-02-22 05:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(UserStorage userStorage, FilmStorage filmStorage) {
Исправлено

2023-02-22 05:33 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        this.userStorage = userStorage;
Исправлено
Установлены цепочки использования контроллер -> сервис -> хранилище

2023-02-22 06:07 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> filterFilms(
Исправлено, метод поиска удален, реализация перенесена на метод findAll

2023-02-22 06:44 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NullPointerException(String.format("Film %d is not found.", filmId));
перенес формирование исключения из хранилища(метод теперь возвращает null) в контроллер

2023-02-22 19:56 UTC, TomattmanYandex approved these changes
Привет, вроде как все хорошо. Принято

2023-03-02 06:55 UTC, merged