Add database
AGolykh/java-filmorate pull request #4
Opened 2023-03-23 05:44 UTC by AGolykh

2023-03-23 15:57 UTC, TomattmanYandex requested changes
Привет
1 - где то должна быть диаграмма базы данных
2 - всю обработку данных лучше оставлять на уровне сервиса, уровень контроллера оставить только для получения данных вызова соответствующего метода из сервиса, и упаковки результата в объект ответа (ну и позже всякие штуки авторизации)
3 - некоторые данные например список друзей и лайков для пользователя или список лайков для фильма не нужно проставлять всегда, так как эти данные нам не нужны всегда, а их проставление вызовет только замедление выполнения, обычно для этого в случае необходимости используется дополнительный запрос с фронта

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (result.isEmpty()) {
лучше сделать эту логику на уровне сервиса, чтобы он возвращал не Optional а просто обьект Film

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public @interface After {
стоит это вынести в отдельные классы
обынчо класс моделей должен отвечать только за хранение данных, и очень часто в них не добавляют вообще никакой дополнительной логики

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public @interface After {
тем более это можно использовать не только с этим классом

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public @interface After {
А еще хорошо бы добавить параметр дату, и сверять с ней, а не по конкретному значению

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +public class Mpa {
этот комментарий просто к сведению
Так как список категорий ограничен и уже полностью определен, то можно было бы обойтись Enum
Но так тоже можно

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +
лишняя пустая строка затесалась

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +                                            "status" BOOLEAN NOT NULL,
что за статус?

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +                                                 PRIMARY KEY ("film_id", "genre_id")
на таблицы использующиеся для связи многие ко многим не обязательно добавлять первичные ключи, потому что они по сути ничего нам не дают, мы не получаем данные из нее просто так, только в связке с другими

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        if (result.isEmpty()) {
снова лучше перекинутьна уровень сервиса

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +        if (result.isEmpty()) {
то же

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        Optional<User> result = userService.findById(userId);
то же

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Qualifier("userDb") private final UserStorage userStorage;
как по мне гораздо проще читается когда аннотация и переменная к которой она относится в разных строках, как минимум потому, что у переменной может быть больше одной аннотации

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return result;
почему бы прямо здесь не прокидывать ту ошибку что прокидывается сейчас на уровне контроллера, и чтобы сам метод возвращал Film 
а с текущей реализацией получается две проверки одного и того же

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        genreFromDb.removeAll(film.getGenres());
тут как то странно воспринимается логика, мы удаляем жанры, но что если жанры привязаны к другому фильму, при обновлении этого они не смогут быть удалены
А если получается что для каждого фильма свой набор жанров, то это уже ошибка нормализации
Если в базе два фильма комедии, то в таблице жанров должна быть только одна запись комедии, а уже к ней привязано несколько фильмов

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Collection<Film> result = filmStorage
это лучше тоже переделать, мы одним запросом можем получить список фильмов с посчитанным количеством лайков, отсортированных по этому количеству, и в количестве ограниченном лимитом

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        likesStorage.like(filmId, userId);
хранилище не должно оперировать такими понятиями как like и dislike на уровне сервиса да, но тут мы создаем запись о том, что вот такой фильм связан вот с таким пользователем и сохраняем в базу, а для дизлайка удаляем из базы

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private Map<String, Long> validateFilmDataRequest(Long filmId, Long userId) {
этот метод тоже лучше переделать
можно в самих методах получать объект, и если он empty то сразу кидать ошибку что объект не найден
а так в множестве случаев, будет  два раза беготня за одними и теми же данными

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Mpa> mpa = mpaStorage.findById(film.getMpa().getId());
1) имя метода очень непонятное, стоит переделать
2) как минимум Mpa можно легко получить в одном запросе с получением фильмов

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        result.forEach(this::makeData);
для каждого фильма будет свой запрос, это плохой подход, так как запросы в базу это одна из самых длительных операций а тут их будет столько же сколько и фильмов в ней
следует сделать один метод, который по списку фильмов получит одним списком все жанры и сразу их ему просетает (это будет логикой на уровне storage)

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Collection<User> findAll() { // вынести оснастку в другой класс
в этом классе все примерно то же что и в filmService

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void makeData(User user) {
Про это я написал в общем коментарии, не уверен что это тут необходимо, тем более что у нас есть дополнительный методы на контроллере для получения списка друзей пользователя

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
>      Collection<Film> findAll(String name, LocalDate after, LocalDate before);
обычно так не поступают, если метод findAll то это значит что найти надо все без всяких фильтров
А если нужны какие то дополнительные фильтрации, то либо пишут отдельные методы для получения по конкретному полю например findByName либо, если уже делать фильтрацию по множеству полей, то метод стоит назвать по другому (но тут пока что эта фильтрация по условию не нужна)

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +    Collection<Genre> findAllByFilmId(Long filmId);
чаще всего если мы добавляем поиск по конкретному полю, то это уже не all 
findByFilmId

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +    void delFilmGenre(Long filmId, Long genreId);
Здесь должна быть шутка про дорогие буквы и нажатия на клавиатуру, и поэтому экономим как можем

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikesStorage.java
> +    void like(Long filmId, Long userId);
про имена этих методов уже писал, хранилище обычно оперирует тем что есть в базе, и не сильно должно знать о бизнес логике

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +/*    public GenreDbStorage(JdbcTemplate jdbcTemplate){
закоменченый код не допускается

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    public Collection<Genre> findAllByFilmId(Long filmId) {
как уже писал в сервисе, но лучше сделать чтобы этот метод принимал список фильмов,
делал один запрос в который будут входить жанры всех фильмов из списка, и проставлял пришедшим фильмам нужные жанры

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +            Genre genre = new Genre(
вот это вот можно перенести в отдельный метод, так как сборка этого обьекта будет происходить в большинстве случаев одинаково

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +        if(findById(genre.getId()).isEmpty()) {
это могла бы быть логика сервиса, сначала получили жанр, чтобы понять есть ли он в базе а потом взвали метода на обновление (но вообще при использовании библиотек для работы с базами обычно на добавление и обновление записи один и тот же метода

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    public void delFilmGenre(Long filmId, Long genreId) {
это мне кажется скорее относится к фильмам чем к жанрам

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    private Genre getGenreFromDb(String name) {
лучше обозвать метод findByName

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikesDbStorage.java
> +    public Collection<Long> getUserLikes(Long userId) {
Это больше относится к пользователю чем к лайкам

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikesDbStorage.java
> +    public Collection<Long> getFilmLikes(Long filmId) {
а это к фильмам

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +    public Collection<Film> findAll(String name, LocalDate after, LocalDate before) {
я уже про это писал в интерфейсе, повторюсь тут, из-за фильтрации чрезмерное усложнение

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +            Film film = new Film(
можно вынести в отдельный метода

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +        if(findById(film.getId()).isEmpty()) {
снова логика сервиса

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +                "ORDER BY \"film_id\" ";
тут следует добавить join для того чтобы сразу получать  Mpa

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/friend/FriendDbStorage.java
> +    public Collection<Long> getFriends(Long userId) {
заменив на запрос с join можно получать не просто id а сразу список пользователей, которые друзья

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/friend/FriendDbStorage.java
> +    public Collection<Long> getCommonFriends(Long userId, Long friendId) {
очень сложно и пугающе 

		final String sqlQuery = "select * from USERS u, FRIENDS f, FRIENDS o " +
				"where u.USER_ID = f.FRIEND_ID AND u.USER_ID = o.FRIEND_ID AND f.USER_ID = ? AND o.USER_ID = ?";

2023-03-23 15:57 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/user/UserDbStorage.java
> +                new User(rs.getLong("user_id"),
создание самого обеькта по резалт сету лучше закинуть в отдельный метод

2023-03-23 17:58 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (result.isEmpty()) {
Исправлено

2023-03-23 18:39 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public @interface After {
Исправлено, создан отдельный класс для валидатора, добавлен функционал задания даты

2023-03-23 18:40 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +
Исправил

2023-03-23 18:43 UTC, AGolykh commented on src/main/resources/schema.sql
> +                                            "status" BOOLEAN NOT NULL,
Согласно ТЗ в таблице должен быть статус, если один пользователь отправил другому запрос, а тот его еще не подтвердил, то false, если второй отправил в ответ запрос первому, то есть подтвердил, то true

2023-03-23 18:48 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        Optional<User> result = userService.findById(userId);
Исправил

2023-03-23 18:49 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Qualifier("userDb") private final UserStorage userStorage;
Исправил

2023-03-23 18:50 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return result;
Исправил

2023-03-23 18:54 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        if (result.isEmpty()) {
Исправил

2023-03-23 18:54 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +        if (result.isEmpty()) {
Исправил

2023-03-23 19:19 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        genreFromDb.removeAll(film.getGenres());
Тут логика такая, что у меня есть база, где прописаны жанры (genres), есть база, где прописаны фильмы(films), a есть база где прописаны id фильмов и id жанров(film_genres), она связана с двумя предыдущими множество-ко-множеству по обоим полям идентификаторов.

Сначала я получаю список жанров, которые есть у фильма в базе, 
Collection<Genre> genreFromDb = genreStorage.findAllByFilmId(film.getId());

затем из этого списка удаляю все жанры, которые есть у обновленного фильма, тем самым находя разницу
genreFromDb.removeAll(film.getGenres());

затем прохожусь по этому списку и удаляю из таблицы (film_genres) строки
genreFromDb.forEach(genre -> genreStorage.delFilmGenre(film.getId(), genre.getId()));

все работает, таблицу фильмов и жанров не трогаю

2023-03-24 04:15 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +    Collection<Genre> findAllByFilmId(Long filmId);
Исправил

2023-03-24 04:17 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +    void delFilmGenre(Long filmId, Long genreId);
написал полностью

2023-03-24 04:18 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +/*    public GenreDbStorage(JdbcTemplate jdbcTemplate){
Исправил

2023-03-24 04:21 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public Collection<User> findAll() { // вынести оснастку в другой класс
Исправил

2023-03-24 04:26 UTC, AGolykh commented on src/main/resources/schema.sql
> +                                                 PRIMARY KEY ("film_id", "genre_id")
Исправил

2023-03-24 04:31 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private Map<String, Long> validateFilmDataRequest(Long filmId, Long userId) {
перенес проверку в метод

2023-03-24 05:09 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +            Genre genre = new Genre(
Исправлено

2023-03-24 05:13 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    private Genre getGenreFromDb(String name) {
Исправлено

2023-03-24 05:35 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/user/UserDbStorage.java
> +                new User(rs.getLong("user_id"),
Исправлено

2023-03-24 05:39 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +            Film film = new Film(
Исправлено

2023-03-24 07:08 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Mpa> mpa = mpaStorage.findById(film.getMpa().getId());
Фильм теперь получает рейтинг из запроса

2023-03-24 07:43 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private void makeData(User user) {
Метод удален ввиду неактуальности

2023-03-24 07:46 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    public void delFilmGenre(Long filmId, Long genreId) {
перенес в фильмы

2023-03-24 07:48 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikesDbStorage.java
> +    public Collection<Long> getUserLikes(Long userId) {
Перенес в юзера

2023-03-24 07:53 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/LikesDbStorage.java
> +    public Collection<Long> getFilmLikes(Long filmId) {
Перенесено в фильмы

2023-03-24 07:54 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +                "ORDER BY \"film_id\" ";
Исправлено

2023-03-24 09:01 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/friend/FriendDbStorage.java
> +    public Collection<Long> getCommonFriends(Long userId, Long friendId) {
Исправлено

2023-03-24 09:53 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Collection<Film> result = filmStorage
Исправлено

2023-03-24 09:55 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
>      Collection<Film> findAll(String name, LocalDate after, LocalDate before);
Исправлено

2023-03-24 09:56 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +    public Collection<Film> findAll(String name, LocalDate after, LocalDate before) {
Исправлено

2023-03-24 10:20 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/friend/FriendDbStorage.java
> +    public Collection<Long> getFriends(Long userId) {
Юзеры теперь получаются запросом, перенесено в юзерс

2023-03-24 11:17 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/film/FilmDbStorage.java
> +        if(findById(film.getId()).isEmpty()) {
Исправлено

2023-03-24 11:21 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +        if(findById(genre.getId()).isEmpty()) {
Логика перенесена в сервис

2023-03-25 12:02 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        likesStorage.like(filmId, userId);
Изменил имена у методов в dao

2023-03-25 12:04 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        result.forEach(this::makeData);
в репозитории создан отдельные методы для расстановки жанров фильму или списку фильмом

2023-03-25 12:12 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/LikesStorage.java
> +    void like(Long filmId, Long userId);
Исправил

2023-03-25 12:12 UTC, AGolykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenreDbStorage.java
> +    public Collection<Genre> findAllByFilmId(Long filmId) {
Сделал

2023-03-26 14:59 UTC, TomattmanYandex approved these changes
Привет, все хорошо, единственные момент, не уверен что теперь нужны классы InMemoryStorage так как теперь вся обработка будет через базу, а оставить их это значит поддерживать еще и эту версию (так что их можно удалить)

2023-03-30 10:18 UTC, merged